"""
Load retail.csv into an in-memory DuckDB connection and return schema context
strings for the LLM prompt.
"""
import re
from pathlib import Path
import duckdb

DATA = Path(__file__).resolve().parent.parent / "data" / "retail.csv"

_con: duckdb.DuckDBPyConnection | None = None


def get_con() -> duckdb.DuckDBPyConnection:
    global _con
    if _con is None:
        _con = duckdb.connect()
        _con.execute(f"""
            CREATE TABLE orders AS
            SELECT
                invoice       AS invoice_no,
                stockcode     AS stock_code,
                description,
                CAST(quantity AS INTEGER) AS quantity,
                invoicedate   AS invoice_date,
                CAST(price AS DOUBLE) AS price,
                customer_id,
                country,
                CAST(revenue AS DOUBLE) AS revenue
            FROM read_csv_auto(
                '{DATA.as_posix()}',
                header=True,
                timestampformat='%Y-%m-%d %H:%M:%S',
                types={{'invoice':'VARCHAR','stockcode':'VARCHAR','customer_id':'VARCHAR'}}
            )
        """)
    return _con


SCHEMA_TEXT = """
Table: orders
Columns:
  invoice_no   VARCHAR  — unique invoice identifier (each invoice = one transaction)
  stock_code   VARCHAR  — product/item code
  description  VARCHAR  — product name/description
  quantity     INTEGER  — units sold (always > 0; cancellations excluded)
  invoice_date TIMESTAMP — transaction datetime (range: 2009-12-01 to 2011-12-09)
  price        DOUBLE   — unit price in GBP (£)
  customer_id  VARCHAR  — customer identifier (NULL for guest/unregistered orders)
  country      VARCHAR  — customer's country (predominantly United Kingdom)
  revenue      DOUBLE   — computed column: quantity × price (in £)

Data: ~400K valid order lines from a UK-based online retailer.
Useful DuckDB date functions: DATE_PART('year', invoice_date), DATE_TRUNC('month', invoice_date),
  STRFTIME(invoice_date, '%Y-%m'), date_diff('day', d1, d2).
For top-N queries use: ORDER BY ... DESC LIMIT N.
Always use double-quoted column names if they contain spaces (none here).
Return results rounded to 2 decimal places for monetary values.
"""


_WRITE_KEYWORDS = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE|ATTACH|COPY|PRAGMA|EXPORT|IMPORT|CALL|GRANT|REVOKE)\b",
    re.IGNORECASE,
)


class UnsafeSQLError(ValueError):
    """Raised when LLM-generated SQL would mutate state instead of just reading it."""


def validate_readonly_sql(sql: str) -> None:
    """Guard against a hallucinated or injected destructive statement being run
    against the shared, process-lifetime DuckDB connection. Every request in
    this app hits the *same* in-memory table (see `_con` above) — a single
    `DROP TABLE orders` or `DELETE FROM orders` generated by the LLM (whether
    from a bad prompt, a genuine hallucination, or a crafted question designed
    to inject one) would corrupt data for every subsequent user until restart.
    Belt: only the first statement's leading keyword must be SELECT/WITH.
    Suspenders: block write/DDL keywords anywhere, including inside a stacked
    `; DROP TABLE ...` second statement.
    """
    stripped = sql.strip().rstrip(";")
    if ";" in stripped:
        raise UnsafeSQLError("Multiple statements are not allowed.")
    first_word = re.match(r"\s*(\w+)", stripped)
    if not first_word or first_word.group(1).upper() not in ("SELECT", "WITH"):
        raise UnsafeSQLError("Only SELECT queries are allowed.")
    if _WRITE_KEYWORDS.search(stripped):
        raise UnsafeSQLError("Query contains a disallowed write/DDL keyword.")


def run_sql(sql: str) -> list[dict]:
    validate_readonly_sql(sql)
    con = get_con()
    result = con.execute(sql).fetchdf()
    return result.to_dict(orient="records")
